version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5477:5432
    volumes:
      - D:\University Build Bright\Year 3\Semester 2\OOP Using Java\Postgres_DB\postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
